AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2   

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 150

Lint/Debugger:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

