name: CI

on:
  push:
    branches:
      - main
      - nywton_barros
  pull_request:
    branches:
      - main
      - nywton_barros
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run RSpec
        run: bundle exec rspec --format documentation

